// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: shelter.proto
//
// NOTE: This is a hand-written stub matching the proto definition.
// Replace with actual generated code via: cd proto && buf generate

package pb

import (
	"context"

	"google.golang.org/grpc"
)

// ShelterServiceClient is the client API for ShelterService.
type ShelterServiceClient interface {
	FindNearest(ctx context.Context, in *NearestRequest, opts ...grpc.CallOption) (*NearestResponse, error)
	GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
}

type shelterServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewShelterServiceClient returns a new ShelterServiceClient bound to the given connection.
func NewShelterServiceClient(cc grpc.ClientConnInterface) ShelterServiceClient {
	return &shelterServiceClient{cc}
}

const (
	shelterServiceFindNearestMethod = "/shelternav.v1.ShelterService/FindNearest"
	shelterServiceGetRouteMethod    = "/shelternav.v1.ShelterService/GetRoute"
)

func (c *shelterServiceClient) FindNearest(ctx context.Context, in *NearestRequest, opts ...grpc.CallOption) (*NearestResponse, error) {
	out := new(NearestResponse)
	err := c.cc.Invoke(ctx, shelterServiceFindNearestMethod, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelterServiceClient) GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, shelterServiceGetRouteMethod, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShelterServiceServer is the server API for ShelterService.
// All implementations must embed UnimplementedShelterServiceServer.
type ShelterServiceServer interface {
	FindNearest(context.Context, *NearestRequest) (*NearestResponse, error)
	GetRoute(context.Context, *RouteRequest) (*RouteResponse, error)
	mustEmbedUnimplementedShelterServiceServer()
}

// UnimplementedShelterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShelterServiceServer struct{}

func (UnimplementedShelterServiceServer) FindNearest(context.Context, *NearestRequest) (*NearestResponse, error) {
	return nil, grpc.ErrServerStopped
}

func (UnimplementedShelterServiceServer) GetRoute(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, grpc.ErrServerStopped
}

func (UnimplementedShelterServiceServer) mustEmbedUnimplementedShelterServiceServer() {}
