// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shelter.proto
//
// NOTE: This is a hand-written stub matching the proto definition.
// Replace with actual generated code via: cd proto && buf generate

package pb

// NearestRequest is the request message for FindNearest.
type NearestRequest struct {
	Lat     float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon     float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusM uint32  `protobuf:"varint,3,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	Limit   uint32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Types   []int32 `protobuf:"varint,5,rep,packed,name=types,proto3" json:"types,omitempty"`
}

// ShelterInfo represents a single shelter in the response.
type ShelterInfo struct {
	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat       float64 `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon       float64 `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Type      int32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Capacity  int32   `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Occupancy int32   `protobuf:"varint,7,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	Status    int32   `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Address   string  `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	DistanceM float64 `protobuf:"fixed64,10,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
}

func (s *ShelterInfo) GetId() int32        { return s.Id }
func (s *ShelterInfo) GetName() string     { return s.Name }
func (s *ShelterInfo) GetLat() float64     { return s.Lat }
func (s *ShelterInfo) GetLon() float64     { return s.Lon }
func (s *ShelterInfo) GetType() int32      { return s.Type }
func (s *ShelterInfo) GetCapacity() int32  { return s.Capacity }
func (s *ShelterInfo) GetOccupancy() int32 { return s.Occupancy }
func (s *ShelterInfo) GetStatus() int32    { return s.Status }
func (s *ShelterInfo) GetAddress() string  { return s.Address }
func (s *ShelterInfo) GetDistanceM() float64 { return s.DistanceM }

// NearestResponse is the response message for FindNearest.
type NearestResponse struct {
	Shelters []*ShelterInfo `protobuf:"bytes,1,rep,name=shelters,proto3" json:"shelters,omitempty"`
}

func (r *NearestResponse) GetShelters() []*ShelterInfo {
	if r != nil {
		return r.Shelters
	}
	return nil
}

// RouteRequest is the request message for GetRoute.
type RouteRequest struct {
	StartLat float64 `protobuf:"fixed64,1,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLon float64 `protobuf:"fixed64,2,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	EndLat   float64 `protobuf:"fixed64,3,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLon   float64 `protobuf:"fixed64,4,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
}

// LatLon represents a geographic coordinate.
type LatLon struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (l *LatLon) GetLat() float64 {
	if l != nil {
		return l.Lat
	}
	return 0
}

func (l *LatLon) GetLon() float64 {
	if l != nil {
		return l.Lon
	}
	return 0
}

// Maneuver represents a single navigation instruction.
type Maneuver struct {
	Point       *LatLon `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Instruction string  `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	DistanceM   float64 `protobuf:"fixed64,3,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
}

func (m *Maneuver) GetPoint() *LatLon {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *Maneuver) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Maneuver) GetDistanceM() float64 {
	if m != nil {
		return m.DistanceM
	}
	return 0
}

// RouteResponse is the response message for GetRoute.
type RouteResponse struct {
	Path             []*LatLon   `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	TotalDistanceM   float64     `protobuf:"fixed64,2,opt,name=total_distance_m,json=totalDistanceM,proto3" json:"total_distance_m,omitempty"`
	EstimatedSeconds uint32      `protobuf:"varint,3,opt,name=estimated_seconds,json=estimatedSeconds,proto3" json:"estimated_seconds,omitempty"`
	Maneuvers        []*Maneuver `protobuf:"bytes,4,rep,name=maneuvers,proto3" json:"maneuvers,omitempty"`
}

func (r *RouteResponse) GetPath() []*LatLon {
	if r != nil {
		return r.Path
	}
	return nil
}

func (r *RouteResponse) GetTotalDistanceM() float64 {
	if r != nil {
		return r.TotalDistanceM
	}
	return 0
}

func (r *RouteResponse) GetEstimatedSeconds() uint32 {
	if r != nil {
		return r.EstimatedSeconds
	}
	return 0
}

func (r *RouteResponse) GetManeuvers() []*Maneuver {
	if r != nil {
		return r.Maneuvers
	}
	return nil
}
